Техническое задание проекта №7
yusuf33nn/java-kanban pull request #2
Opened 2024-12-17 21:40 UTC by yusuf33nn

sprint_7-solution-in-file-manager: добавить исключение, новую реализацию TaskManager, переместить файлы в нужные папки, добавить папку resources

2024-12-18 19:14 UTC, Yang-Pi commented on src/main/java/utils/Managers.java
> +        Типа файл сохранился, программа перезапустилась и надо засунуть все таски по всем мапам?
да, все верно

2024-12-18 19:20 UTC, Yang-Pi commented on src/main/java/utils/Managers.java
>  public class Managers {
public static TaskManager getDefault() реализацию InMemoryTasksManager лучше заменить на FileBackedTasksManager

2024-12-18 19:21 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +        //TODO а этот метод как раз, чтобы превратить строку из csv в объект Task и добавить его в мапу?
только превратить в объект Task, добавление в мапу вне этого метода, иначе нарушается принцип single responsibility

2024-12-18 19:22 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +        //TODO здесь через instanceOf?
нет, через ООП) можно переопределить метод toString() в классе Task, а также в его наследниках

2024-12-18 19:25 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +                Files.writeString(path, "id,type,name,status,description,epic\n");
нужно воспользоваться BufferedWriter и записать в файл все коллекции тасок

2024-12-18 19:25 UTC, Yang-Pi requested changes
жду реализацию, на вопросы ответил

2024-12-23 18:09 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +        //TODO Я правильно понял, что после каждого update, добавления записи - мне надо очищать файл и добавлять всё по новой?
конечно, каждое изменение (в том числе и удаление) должно быть отражено в файле. Иначе будет неконсистентное состояние. В случае с базами данных, которые будут в следующих работах, обновления данных происходит более оптимально. Здесь же в качестве ознакомления мы работаем с файлом. Нет требований к идентификации строк в файле, поэтому после каждого изменения перезаписываем его. Достаточно переопределить методы create update delete, добавив после вызова super вызов метода save()

2024-12-23 18:11 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +                bw.write("id,type,name,status,description,epic\n");
каждый список задач необходимо вписать в файл

2024-12-23 18:16 UTC, Yang-Pi commented on src/main/java/models/Task.java
> +        /*TODO я не понимаю как здесь сделать без instanceOf????
у любого объекта есть метод toString() (кстати советую почитать по первой ссылке в гугле про основные методы Object в Java - очень популярный вопрос на собеседовании).
в классе Task (который является наследником класса Object) мы можем переопределить метод toString(), выводя те данные которые нам интересны. В наследниках класса Task точно так же переопределяем toString(), если нужно выводить какие-то дополнительные поля. 
toString() вызывается на объекте, поэтому параметр task не нужен. toString() - без параметров.

затем просто вызовешь task.toString() у любой задачи, которую нужно превратить строку при записи ее в файл

2024-12-23 18:19 UTC, Yang-Pi commented on src/main/java/manager/InMemoryTaskManager.java
> +        long taskId = task.getId();
при сохранении мы в любом случае используем собственную последовательность TASK_ID_COUNTER для генерации очередного id. Лучше не брать id из параметра task, так как он может конфликтовать с уже существующими

2024-12-23 18:24 UTC, Yang-Pi commented on src/main/java/manager/FileBackedTaskManager.java
> +        } catch (IOException e) {
внутри try может быть выкинуто не только IOException, лучше обработать еще и общий случай с Exception, залогировать его (в консоль) и прокинуть дальше, чтобы программа аварийно завершилась. Например это может быть ошибка, когда TaskType.valueOf не найдет подходящий тип по строке

2024-12-23 18:28 UTC, Yang-Pi commented on src/main/java/Main.java
> +        //TODO правильно я понял - так надо загружать из файла при запуске?
да

2024-12-25 13:51 UTC, yusuf33nn commented on src/main/java/manager/FileBackedTaskManager.java
> +                bw.write("id,type,name,status,description,epic\n");
@Yang-Pi 
не очень понял, что это значит?

2024-12-29 07:50 UTC, Yang-Pi approved these changes

2024-12-29 17:04 UTC, merged